### ISSUE TITLE
Firefox version renders as "24." instead of "24"

### ISSUE THREAD

**Issue by Krinkle** [WordPress/browsehappy#11]
Somehow the parsing logic in browsehappy's PHP code seems to *add* a dot if the input from Wikipedia is a round number (the template changed from `23.0` to `24`).

Fixed [it on Wikipedia](https://en.wikipedia.org/w/index.php?title=Template%3ALatest_stable_software_release%2FFirefox&diff=573642284&oldid=573325991) for now, but in general this should be fixed on this side.

**Comment by coffee2code** [comment]
Thanks for the report and fixing the issue on the Wikipedia side of things at the time!

I've been unable to reproduce the issue with the current codebase when simulating a latest release version number expressed as a whole number (as provided in the before of the change performed in the above Wikipedia link). Looks not to be an issue any longer.
