### ISSUE TITLE
Facebook like button below Safari is missing.

### ISSUE THREAD

**Issue by sudheesh001** [WordPress/browsehappy#17]
the div for `class="pluginButtonContainer"` doesn't appear below Safari
![screen shot 2014-07-06 at 2 14 55 pm](https://cloud.githubusercontent.com/assets/4545925/3488730/d2b730ca-04fe-11e4-9178-2b010158fbd7.png)

**Comment by coffee2code** [comment]
Thanks for the report! However, this is not an issue. Safari does not have an official Facebook page so it can't really have a like button.
