### ISSUE TITLE
Twitter logo updated in #9 isn't reflected on the website.

### ISSUE THREAD

**Issue by sudheesh001** [WordPress/browsehappy#18]
Commit where the fix was made b26ec563a20488cc2c8d3a01a40ed8433b40eabb
![screen shot 2014-07-06 at 2 25 28 pm](https://cloud.githubusercontent.com/assets/4545925/3488758/4259907a-0500-11e4-9601-004517d09f7c.png)

**Comment by Otto42** [comment]
Issue #9 is not closed, and that change has not been committed. Making another issue for an open issue doesn't make much sense.
