### ISSUE TITLE
Safari descriptions outdated

### ISSUE THREAD

**Issue by xeniun** [WordPress/browsehappy#20]
Safari is not released anymore for Windows!
Please, update translation correctly.

“Safari for Mac from Apple, the world’s most innovative browser.” in
"Safari per Mac da Apple, il browser più innovativo del mondo".

In reality descriptions are all messy and not right.

**Comment by scheinercc** [comment]
I would change this ticket to "Description for Safari outdated". Now that the OS name has changed it could read:
“Safari for macOS from Apple, the world’s most innovative browser.”

The German version would change to:
“Safari für macOS von Apple, der weltweit innovativste Browser.”
