### ISSUE TITLE
Safari 7+ has a different icon

### ISSUE THREAD

**Issue by mzgol** [WordPress/browsehappy#26]
Safari 7+ has a different icon than the one displayed on the site. The current one is available at https://raw.githubusercontent.com/alrra/browser-logos/master/safari/safari.png:
![Safari 9 icon](https://raw.githubusercontent.com/alrra/browser-logos/master/safari/safari.png)

**Comment by Otto42** [comment]
Duplicate of #25

**Comment by mzgol** [comment]
That's what I get for searching in issues only instead of in PRs as well. Sorry!
