### ISSUE TITLE
Can't access site via https

### ISSUE THREAD

**Issue by liamness** [WordPress/browsehappy#27]
Tried in a few browsers, they will complain that the certificate is invalid. If you press ahead regardless, you get redirected to an error page.

**Comment by cwonrails** [comment]
Same issue here. My site is https-only with http/2. I would love to use browsehappy but I'd prefer not to have mixed content warnings.

**Comment by NoMan2000** [comment]
@coffee2code Can this get fixed?  There are free certs from https://letsencrypt.org/

**Comment by dAnjou** [comment]
I think this is extremely important because you're pointing users to software that they are supposed to download and install. Without HTTPS there's no way of knowing whether a MITM is trying to redirect them to corrupted browser downloads.

**Comment by coffee2code** [comment]
Apologies for the belated follow-up. HTTPS has been enabled and enforced on the site for a few months by now at least, so closing as fixed.
