### ISSUE TITLE
Use official `Internet Explorer` logo

### ISSUE THREAD

**Issue by alrra** [WordPress/browsehappy#33]
[Currently](https://cloud.githubusercontent.com/assets/1223565/14622984/c4c1a8da-05d6-11e6-9fba-ec8ce6c291df.png), `Browse Happy` doesn't use the official `Internet Explorer` logo.

| [Internet Explorer `9 - 11` logo](https://github.com/alrra/browser-logos/tree/0ab9dd33af1a4df2b671f31ee2b37f4e25d05eb6/internet-explorer) |
| :-: |
| <a href="https://github.com/alrra/browser-logos/tree/0ab9dd33af1a4df2b671f31ee2b37f4e25d05eb6/internet-explorer"><img width=300 height=300 src="https://cloud.githubusercontent.com/assets/1223565/14622912/27c04140-05d6-11e6-8613-aa7c73a152c2.png"></a> |

**Comment by coffee2code** [comment]
Thanks @alrra for your browser-logos repo and contributions!

In this particular case, I'm a bit dubious of the suggested use of this version of the IE logo. The version currently employed on Browse Happy seems to be the latest one in use by Microsoft. For instance, the [WikiPedia page for Internet Explorer 11](https://en.wikipedia.org/wiki/Internet_Explorer_11) shows our in-use logo as the app's logo as well as a screenshot of the logo in use on the "About Internet Explorer" popup (for IE 11 running on Windows 10).

Another example of the currently used logo version as being valid: http://logos.wikia.com/wiki/Internet_Explorer

The above logo seems to be more closely associated with [Internet Explorer 9](https://en.wikipedia.org/wiki/Internet_Explorer_9). Assuming at worst that both logos are valid, I prefer the version we're using.
