### ISSUE TITLE
Visiting browsehappy.com shows a 403 Forbidden error

### ISSUE THREAD

**Issue by smpetrey** [WordPress/browsehappy#43]
I'm currently seeing a 403 Forbidden Error when I visit the root URL 
![screenshot 2017-10-24 17 22 47](https://user-images.githubusercontent.com/6411509/31968708-fbafe538-b8df-11e7-9a6c-7af65b854c31.png)

**Comment by coffee2code** [comment]
@smpetrey : Thanks for the report! We have a request in to the site's systems team and will follow-up here once the issue is resolved.

**Comment by alisterscott** [comment]
@smpetrey I'm no longer seeing this issue. Can you please confirm that it is fixed for you also?

**Comment by smpetrey** [comment]
@coffee2code @alisterscott can confirm, 403 has been banished! 🎉
