### ISSUE TITLE
Modify the zh-cn page

### ISSUE THREAD

**Issue by wordlesswind** [WordPress/browsehappy#46]
We cannot view google.com in China, and other browsers have dedicated Chinese websites.

Chrome: https://www.google.cn/chrome
Firefox: https://www.firefox.com.cn
Opera: http://www.oupeng.com

**Comment by paperbag** [comment]
- First, Firefox and Opera websites are not blocked in China.
- Secondly, `www.firefox.com.cn` provide install-package **not same as** `www.firefox.com`. People use `www.firefox.com.cn` can't log in Firefox Account! Please learn more about that.

**Comment by wordlesswind** [comment]
time out
