### ISSUE TITLE
Remove IE11

### ISSUE THREAD

**Issue by jaydenseric** [WordPress/browsehappy#49]
The point of Browse Happy is to encourage users to adopt up-to-date browsers that support modern web standards, for a better user and developer experience.

By putting IE11 next to the icons of all the other browsers it is creating the false impression it is an equivalent choice.

IE11 is a dead browser, Microsoft themselves are encouraging people to abandon it. Just because Microsoft will continue to provide security patches for corporate users does not mean it is being kept up to date with modern web standards or that it is a good browser for consumers to use by choice.

Sure, some people who don't use an up-to-date version of Windows can't upgrade to Edge, but frankly that's their problem. Even MS-DOS is still used in places in the world and it can't use any of the listed browsers. Besides, they can update to something other than Edge such as Firefox or Chrome.

**Comment by jaydenseric** [comment]
For what it's worth, http://outdatedbrowser.com does not display IE.

**Comment by apokryfos** [comment]
End of life for Windows 8 is in 2023 and since people on windows 8 (or 7) can't use edge it might be better to show IE for windows 7 - 8 users and edge for windows 10 if at all possible.

**Comment by JoshuaGoode** [comment]
A more recent discussion on the perils of using IE from Microsoft:

* https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732

* https://www.techradar.com/news/microsoft-begs-users-to-stop-using-internet-explorer

**Comment by ntwb** [comment]
See also https://meta.trac.wordpress.org/ticket/4863
> Adding a notice do discourage IE11 usage
