### ISSUE TITLE
Wordpress Website is not loading correctly..

### ISSUE THREAD

**Issue by zosia1990** [WordPress/browsehappy#55]
Hi,

I'm struggling with website I created in Wordpress. The website is loading content differently after each reload on every page and browser. I contacted with theme support and they told me to delete all browser and Wordpress cache etc. It doesn't help at all.. I checked website on my friends computers and different browsers, cleared all cache and everywhere I checked website 
Some of people I asked to check website is having trouble loading the website or a particular page of the website.

I'm just curious is this happening because website can't load css ?

https://czestochowa.us/

I really appreciate any help. THANKS !

**Comment by coffee2code** [comment]
Sorry to hear you've experienced trouble using WordPress on your own site. However, this particularly repository is dedicated to the development of the theme for the Browse Happy site.

You should be able to find help through the WordPress project's official support site at https://wordpress.org/support/.

Cheers!
