### ISSUE TITLE
Recommend Chromium-based Edge instead of EdgeHTML

### ISSUE THREAD

**Issue by katlou** [WordPress/browsehappy#61]
Hey there!

I wonder if there's a reason behind recommending the latest EdgeHTML version of Edge (last stable release in November 2019) instead of the new Blink version of Edge (last stable release April 2020). I'm happy to make the edits.

Thanks,
Katherine

**Comment by patocallaghan** [comment]
@coffee2code any update on this one? I'd also love to see this change considering Microsoft are now pushing Edge Chromium out to all their users over Windows Update.
